import { v4 as uuid } from 'uuid';

export const defaultCategories = [
  {
    id: uuid(),
    userId: null,
    name: 'Еда и продукты',
    type: 'expense',
    icon: '🍔',
  },
  {
    id: uuid(),
    userId: null,
    name: 'Транспорт',
    type: 'expense',
    icon: '🚕',
  },
  {
    id: uuid(),
    userId: null,
    name: 'Покупки',
    type: 'expense',
    icon: '🛍',
  },
  {
    id: uuid(),
    userId: null,
    name: 'Развлечения',
    type: 'expense',
    icon: '🎬',
  },
  {
    id: uuid(),
    userId: null,
    name: 'Здоровье',
    type: 'expense',
    icon: '💊',
  },
  {
    id: uuid(),
    userId: null,
    name: 'Счета и услуги',
    type: 'expense',
    icon: '🧾',
  },
  {
    id: uuid(),
    userId: null,
    name: 'Образование',
    type: 'expense',
    icon: '📚',
  },
  {
    id: uuid(),
    userId: null,
    name: 'Другое',
    type: 'expense',
    icon: '📦',
  },
  {
    id: uuid(),
    userId: null,
    name: 'Зарплата',
    type: 'income',
    icon: '💼',
  },
  {
    id: uuid(),
    userId: null,
    name: 'Фриланс',
    type: 'income',
    icon: '💻',
  },
  {
    id: uuid(),
    userId: null,
    name: 'Бизнес',
    type: 'income',
    icon: '🏢',
  },
  {
    id: uuid(),
    userId: null,
    name: 'Инвестиции',
    type: 'income',
    icon: '📈',
  },
  {
    id: uuid(),
    userId: null,
    name: 'Подарки',
    type: 'income',
    icon: '🎁',
  },
  {
    id: uuid(),
    userId: null,
    name: 'Другое',
    type: 'income',
    icon: '💰',
  },
];
